# Generated by Django 3.1.1 on 2023-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('referencenumber', models.CharField(help_text='reference number', max_length=20)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
